--PROCEDURE PARA CADASTRAR PRODUTO
CREATE PROCEDURE SP_INSERIR_PRODUTO
	@ID			UNIQUEIDENTIFIER,
	@NOME		VARCHAR(100),
	@PRECO		DECIMAL(10,2),
	@QUANTIDADE	INT,
	@ESTOQUE_ID	UNIQUEIDENTIFIER
AS
BEGIN
	--VERIFICANDO SE NÃO EXISTE O ESTOQUE INFORMADO
	IF NOT EXISTS (SELECT 1 FROM ESTOQUE WHERE ID = @ESTOQUE_ID)
	BEGIN
		--LANÇAR UM ERRO (EXCEÇÃO)
		RAISERROR ('Estoque não encontrado. Verifique o ID informado', 16, 1);
		RETURN;
	END

	--INSERIR O PRODUTO NO BANCO DE DADOS
	INSERT INTO PRODUTO(ID, NOME, PRECO, QUANTIDADE, ESTOQUE_ID)
	VALUES(@ID, @NOME, @PRECO, @QUANTIDADE, @ESTOQUE_ID);
END
GO

--PROCEDURE PARA ATUALIZAR PRODUTO
CREATE PROCEDURE SP_ALTERAR_PRODUTO
	@ID			UNIQUEIDENTIFIER,
	@NOME		VARCHAR(100),
	@PRECO		DECIMAL(10,2),
	@QUANTIDADE	INT,
	@ESTOQUE_ID	UNIQUEIDENTIFIER
AS
BEGIN
	--VERIFICANDO SE NÃO EXISTE O PRODUTO INFORMADO
	IF NOT EXISTS (SELECT 1 FROM PRODUTO WHERE ID = @ID)
	BEGIN
		--LANÇAR UM ERRO (EXCEÇÃO)
		RAISERROR ('Produto não encontrado. Verifique o ID informado', 16, 1);
		RETURN;
	END

	--VERIFICANDO SE NÃO EXISTE O ESTOQUE INFORMADO
	IF NOT EXISTS (SELECT 1 FROM ESTOQUE WHERE ID = @ESTOQUE_ID)
	BEGIN
		--LANÇAR UM ERRO (EXCEÇÃO)
		RAISERROR ('Estoque não encontrado. Verifique o ID informado', 16, 1);
		RETURN;
	END

	--ATUALIZAR O PRODUTO NO BANCO DE DADOS
	UPDATE PRODUTO
	SET
		NOME = @NOME,
		PRECO = @PRECO,
		QUANTIDADE = @QUANTIDADE,
		ESTOQUE_ID = @ESTOQUE_ID
	WHERE
		ID = @ID;
END
GO

--PROCEDURE PARA EXCLUIR PRODUTO
CREATE PROCEDURE SP_EXCLUIR_PRODUTO
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	--VERIFICANDO SE NÃO EXISTE O PRODUTO INFORMADO
	IF NOT EXISTS (SELECT 1 FROM PRODUTO WHERE ID = @ID)
	BEGIN
		--LANÇAR UM ERRO (EXCEÇÃO)
		RAISERROR ('Produto não encontrado. Verifique o ID informado', 16, 1);
		RETURN;
	END

	--EXCLUIR O PRODUTO NO BANCO DE DADOS
	DELETE FROM PRODUTO WHERE ID = @ID;
END
GO