--CRIAÇÃO DA TABELA DE ESTOQUE
CREATE TABLE ESTOQUE(
	ID			UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME		VARCHAR(50)			NOT NULL);
GO

--CRIAÇÃO DA TABELA DE PRODUTO
CREATE TABLE PRODUTO(
	ID			UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME		VARCHAR(100)		NOT NULL,
	PRECO		DECIMAL(10,2)		NOT NULL,
	QUANTIDADE	INT					NOT NULL,
	ESTOQUE_ID	UNIQUEIDENTIFIER	NOT NULL,
	FOREIGN KEY(ESTOQUE_ID)
		REFERENCES ESTOQUE(ID));
GO